### ISSUE TITLE
Update – World Position

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#154]
ASE World Position Node Returns the surface position in world space 
please add option to return Absolute World space position

Note with in SG 
HDRP uses [Camera Relative] as its default world space
URP uses Absolute World as its default world space

https://docs.unity3d.com/Packages/com.unity.shadergraph@15.0/manual/Position-Node.html

ASE vs SG (Object, View, World, Tangent, Absolute World)

ASE xxxxxx + Transform Position = SG Position Node (Object)
ASE xxxxxx + Transform Position = SG Position Node (View)
ASE World Position = SG Position Node (World)
ASE Vertex Position = SG Position Node (Tangent)

ASE ______________ = SG Position Node (Absolute World)

**Comment by BOXOPHOBIC** [comment]
ASE World Position always returns absolute world position.
Ase could add a simple function to match the Position node in SG if this is really needed, but ll of them cam be achieved with transformations.

@Dawie3565 

ASE Vertex Position  = SG Position Node (Object)
ASE World Position = SG Position Node (Absolute World)

ASE Vertex Position + Transform Position Object to World = SG Position Node (Absolute World)
ASE Vertex Position + Transform Position Object to View = SG Position Node (View)
ASE Vertex Postion + Transform Position Object to Tangent = SG Position Node (Tangent)

// These are not desired because first it is transformed to world then back to other spaces
ASE World Position + Transform Position World to View = SG Position Node (View)
ASE World Position + Transform Position World to Tangent = SG Position Node (Tangent)

SG Position Node (World) uses the camera relative rendering which is only available in HDRP

**Comment by Dawie3565** [comment]
@BOXOPHOBIC Correct this is part of a first step in a larger systematic review process thru all nodes from ASE vs SG and UE5
we identified gaps during the review and generate actions to continue even deeper review or as specified

**Comment by Dawie3565** [comment]
closed 
to make same as SG use vertex position and transform position like this 
http://paste.amplify.pt/view/raw/e17929b3
![image](https://github.com/user-attachments/assets/41202c73-b9bd-46ca-9f4b-c8de6bbd3d4b)
