### ISSUE TITLE
Review and update logic for blend modes

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#224]
review and update logic for blend modes in BIRP
Review logic for custom to not auto change blend alpha mode to pre multiplied with Scr/One Dst/One Minus Src Alpha and maintain the custom option.

for details see sub chat with user urano

**Comment by diogovtx** [comment]
This is expected behavior. Not a bug.

Premultiplied corresponds to Src: One / Dst: OneMinusSrcAlpha. It's merely a label/shortcut identifying the type of formula that is being used. This label doesn't affect anything about the way blend mode works, it's merely a shortcut. User still has full control over the formula and should ignore the label when setting up the formula manually, since it keeps changing depending on whether it's a recognizable blend mode or not. If the blend mode is not recognized then "Custom" is used, otherwise the correct name is used.
