### ISSUE TITLE
Instance ID Node HDRP URP

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#291]
Instance ID Node returns errors in HDRP/URP when connected to vertex output 

error 
Shader error in 'New Amplify Shader': 'VertexFunction': no matching 1 parameter function at line xxxxx

to replicate connect node to vertex output 
set USE SV semantic = True 
compile

**Comment by Dawie3565** [comment]
Note error only happens when checked "Use SV sematic"
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/acee0da4-770f-4cb8-b607-cc1690fed948)

**Comment by naelstrof** [comment]
I've discovered a bit more information about this bug, this is in context to getting the shader to work with RenderPrimitives and RenderMeshPrimitives.

1. The sv semantic style shader was required for Unity version 2022.3.10f1, as its RenderPrimitives and RenderMeshPrimitives don't seem to work without it. (Probable unity bug?)

2. The sv semantic option is NOT required for Unity version 2022.3.21f1. Instead, the "Instanced Terrain" option simply needs to be enabled.

I've upgraded my Unity project, disabled the sv semantic option, and enabled *Instanced Terrain*, and now RenderPrimitives works wonderfully.

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/1131571/eef12633-df5d-4959-9a15-a05aaf1b6ae3)

Now I can render all the grass!
You can find a minimal project here that has everything needed to test the bug: <https://github.com/naelstrof/UnityFlocking>
With a RenderMeshPrimitives version at <https://github.com/naelstrof/UnityFlocking/commit/1e0dc925f5c5241d333c8811ce2e6d1eb0bb6fb4>
And a RenderPrimitives version at the head.

Thank you again!

**Comment by Dawie3565** [comment]
moved to 1.9.3.5

**Comment by Dawie3565** [comment]
**Bumped Git item 291 with new tag Critical** 
--- breaking asset MudBun in BIRP 2022.3.25
when progressed contact in discord "Kamgam"

Error invalid ds_5_0 input semantic 'SV_VertexID'
Note change in shader model would not fix

**Comment by diogovtx** [comment]
These are not the same issue. Added a separate issue for VertexID #328 .

**Comment by kamgam** [comment]
Hi, I am the dev behind kamgam. I have seen your changelogs in Amplify 1.9.6.3 on the store and thought I'd give it a try. Though sadly the bug (or a related one) still exists. What may be of interest is that I can now use the vertex POSITION but as soon as I use the vertex NORMAL I get the error again. Maybe applying the fix to the normals was missed (just a wildguess)? Also intersting to note, if I turn OFF tessellation it works (makes sense since the error originated in the HULL function).

The concrete error I get is this:

> Shader error in 'SkyClouds_MudBun': invalid hs_5_0 control point output semantic 'SV_VertexID' invalid hs_5_0 control point input semantic 'SV_VertexID' invalid hs_5_0 control point input semantic 'SV_VertexID' invalid hs_5_0 control point input semantic 'SV_VertexID' at line 2415 (on d3d11)
> 
> Compiling Subshader: 0, Pass: Meta, Hull program with <no keywords>
> Platform defines: SHADER_API_DESKTOP UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_PASS_META UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS
> Disabled keywords: EDITOR_VISUALIZATION MUDBUN_PROCEDURAL SHADER_API_GLES30 UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_VIRTUAL_TEXTURING

Am testing on Unity 2022.3.15f1 (URP 14.0.11). Amplify 1.9.6.3.
If you want I can export a demo project for you. The error happens if I try to use the "Mud Mesh" node of [MudBun](https://assetstore.unity.com/packages/tools/particles-effects/mudbun-volumetric-vfx-modeling-177891) to gather vertex normals from the MudMesh. They use the Vectex ID node for their "Mud Mesh" with a Custom Expression node (I do not want to share their code here publicly but it's not a complicated node, not sure if it's related to the error).

![image](https://github.com/user-attachments/assets/e01eff38-df74-4ee4-ba30-4c0653f4d120)

Side Note (maybe a different issue): I tried to draw the NORMALS I get from the MudBun node (which fetches the normals based on the Vertex ID). This is what I get:
![image](https://github.com/user-attachments/assets/786b2e05-eeb7-4c22-81a6-d2585250bf62)
So some normals look okay-ish but most are messed up and they also change depending on the camera viewing angle (which they shouldn't). On this one I am not sure if Amplify or MudBun is to blame. Maybe it's related to the normals issue in the hull function, not sure (the shader in the image above does not use tessellation since that gives the compile error).

Thank you. Please let me know how I can help resolve this issue :-)

**Comment by diogovtx** [comment]
@kamgam this is about a different issue, regarding Instance ID. That specific case, regarding VertexID is issue https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/328.

Unfortunately, I was unable to get to it yet, but things are finally speeding up again and I should be able to get it fixed on v1.9.8. It's a complicated fix, thus the delay.
