### ISSUE TITLE
Matrix Default values 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#335]
check default values for **(New)** matrix nodes 
Matrix 3
Matrix 4 

check default values for **(new)** shader function matrix inputs
Matrix 3
Matrix 4

**Comment by OwenTheProgrammer** [comment]
Copy/Pasting of Matrix 3x3 and Matrix 4x4 function inputs also seem problematic, seems like an alignment issue internally

**Comment by diogovtx** [comment]
This turned out to be a weird way of preserving/copying values between different types when changing the Function Input's data type.

I created an exception for matrices, where non-matrix values simply aren't copied/matched in this case. When dealing will matrices, values will only be preserved when changing from float3x3 to float4x4, and vice-versa.

Other than that, matrix defaults are generally fine.
