### ISSUE TITLE
ASE function "World Normal Face"

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#354]
ASE function "World Normal Face"

--1-- Change name from "World Normal Face" to "Face Normal" to match same as Unity SG
--2-- Remove world space Camera Pos as it is not part of function and breaks in use with decals
--3-- Update per latest changes to match Unity SG adding Space sub options 

Link:
http://paste.amplify.pt/view/raw/3f511519

![image](https://github.com/user-attachments/assets/4bbcf66d-7653-4edc-8e47-7f5844573698)

Note this function is used a lot in SRP decals as decals don't have a vertex normal, so we use the Face Normal node to derive the approximate world space normal of the surfaces that the decal intersects. adding any world space Camera Pos breaks this intended use  and main reason for it to be removed and match same as Unity SG.

**Comment by diogovtx** [comment]
Implemented 1 and 3. Kept 2 because it's [important for precision](https://www.enkisoftware.com/devlogpost-20150131-1-Normal-generation-in-the-pixel-shader) and should not break in any case. I did fix it to ensure the translation to view space happens before interpolation.

Didn't change the name, because it would create conflicts due to unitypackages. Instead, I added these changes to new node, derived from "World Normal Face", named "Normal Face".
